version: "3.8"
services:
  firefox: 
    image: selenium/node-firefox:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=nginx:8080
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
     - "84442:4442"
     - "4443:4443"
     - "4444:4444"

  docker-apache:
    image: my-php-site:latest
    container_name: docker-apache
    ports:
      - "80:80"

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_DATABASE: badcrud
    ports:
      - "3306:3306"
    volumes:
      - ./db/badcrud.sql:/docker-entrypoint-initdb.d/badcrud.sql:ro
